version: "3"

services:
#######################
#        AMZAIR       #
#######################
    http-amzair:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /var/www/amzair-api:/var/www/amzair
            - /var/www/amzair-api/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-amzair:php
        networks:
            - amzair
    php-amzair:
        build: .
        working_dir: /var/www/amzair
        volumes:
            - /var/www/amzair-api:/var/www/amzair
        links:
            - mysql-amzair:db
        networks:
            - amzair
    mysql-amzair:
        image: mysql:latest
        command: --sql_mode=""
        ports:
            - "8090:3306"
        volumes:
            - /var/www/amzair-api/db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: amzair
        networks:
            - amzair
networks:
    amzair:
        external: true
